version: "3.8"
services:
  my-spring-app:
    image: alexroza/api_book:pipeline-1.0
    ports:
      - 8088:8088
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD:password
      - POSTGRES_DB:apibook